// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq90RVkgbe-HzRwzkolvpk15dWd11xFA0',
    appId: '1:124598436116:web:2c76851826fb692f354201',
    messagingSenderId: '124598436116',
    projectId: 'rapidresq-90a10',
    authDomain: 'rapidresq-90a10.firebaseapp.com',
    storageBucket: 'rapidresq-90a10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaTHLSR9rQwSIlYZEeuJRF2jdbInCaN4A',
    appId: '1:124598436116:android:93738e388963d82a354201',
    messagingSenderId: '124598436116',
    projectId: 'rapidresq-90a10',
    storageBucket: 'rapidresq-90a10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxUxUW2hJTRxwVQywnCqLH9o3-7xOiOFk',
    appId: '1:124598436116:ios:8fb7f66ec684487f354201',
    messagingSenderId: '124598436116',
    projectId: 'rapidresq-90a10',
    storageBucket: 'rapidresq-90a10.firebasestorage.app',
    iosBundleId: 'com.example.rapidresqPatient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxUxUW2hJTRxwVQywnCqLH9o3-7xOiOFk',
    appId: '1:124598436116:ios:8fb7f66ec684487f354201',
    messagingSenderId: '124598436116',
    projectId: 'rapidresq-90a10',
    storageBucket: 'rapidresq-90a10.firebasestorage.app',
    iosBundleId: 'com.example.rapidresqPatient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq90RVkgbe-HzRwzkolvpk15dWd11xFA0',
    appId: '1:124598436116:web:2c76851826fb692f354201',
    messagingSenderId: '124598436116',
    projectId: 'rapidresq-90a10',
    authDomain: 'rapidresq-90a10.firebaseapp.com',
    storageBucket: 'rapidresq-90a10.firebasestorage.app',
  );
}